version: '3'

services:

  app:
    image: aaguirre/app:latest
    links:
      - redis:redis
    networks:
      - default
    restart: always
    ports: 
      - "8080:8080"
    volumes:
      - ./puppy.jpg:/var/puppy.jpg

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default
    restart: always

  nginx:
    image: nginx:alpine
    command: ["nginx", "-g", "daemon off;"]
    links:
      - app:app
    ports:
      - "80:80"
    networks:
      - default
    restart: always
    volumes: 
     - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: overlay

